services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_QUERY_PROFESSORS_URL_PROD=http://0.0.0.0:8000/get_professors
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge