[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pinecone>=7.0.1",
    "pydantic>=2.11.4",
    "sentence-transformers",
    "supabase>=2.15.2",
]
