[project]
name = "web_scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.33.0",
    "stealth>=0.0.1",
]
